[build]
  command = "npm run build"
  publish = "dist"
  base = "frontend"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Mobile performance headers
    Cache-Control = "public, max-age=0, must-revalidate"
    # Enable compression
    Accept-Encoding = "gzip, br"

# Service Worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Disable Netlify analytics injections that might cause issues
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

